### ISSUE TITLE
match_naive counts FNs wrongly when match_other = True

### ISSUE THREAD

**Issue by jjavier-bm** [rigdenlab/conkit#113] opened 2022-06-01 10:44 UTC
## General Information

- ConKit version: 0.13.3
- Python version: 10.3
- Environment (if applicable): Anaconda

## Example

A minimal example to reproduce the error:
- Files: [https://www.dropbox.com/s/kq0e6milkaqbsa7/1bja_minimal.zip?dl=0](https://www.dropbox.com/s/kq0e6milkaqbsa7/1bja_minimal.zip?dl=0)
```
>>> from conkit import io as ckio

>>> cmap = ckio.read('1bja.deepmetapsicov.psicov', 'psicov')[0]
>>> smap = ckio.read('1bja.interface.1.pdb', 'pdb')[0].as_contactmap()
>>> seq = ckio.read('1bja_1.fasta', 'fasta')[0]

>>> cmap.sequence = seq
>>> cmap.set_sequence_register()

>>> cmap.match_naive(smap, add_false_negatives=True, inplace=True, match_other=True)  # First attempt with add_false_negatives = True

>>> cnts = {'tp': 0, 'tn': 0, 'fp': 0, 'fn': 0}

>>> for contact in cmap:
        if contact.true_positive:
            cnts['tp'] += 1
        elif contact.false_positive:
            cnts['fp'] += 1
        elif contact.false_negative:
            cnts['fn'] += 1
        elif contact.true_negative:
            cnts['tn'] += 1
        else:
            continue

>>> cnts  # {'tp': 105, 'tn': 0, 'fp': 2950, 'fn': 338}

>>> for contact in smap:
        if contact.true_positive:
            cnts['tp'] += 1
        elif contact.false_positive:
            cnts['fp'] += 1
        elif contact.false_negative:
            cnts['fn'] += 1
        elif contact.true_negative:
            cnts['tn'] += 1
        else:
            continue

>>> cnts  # {'tp': 210, 'tn': 0, 'fp': 2950, 'fn': 676} --> Doubles FPs and FNs (they appear in both maps). FPs not appearing in structure. AS EXPECTED.

# HOWEVER

>>> cmap = ckio.read('1bja.deepmetapsicov.psicov', 'psicov')[0]
>>> smap = ckio.read('1bja.interface.1.pdb', 'pdb')[0].as_contactmap()
>>> seq = ckio.read('1bja_1.fasta', 'fasta')[0]

>>> cmap.sequence = seq
>>> cmap.set_sequence_register()

>>> cmap.match_naive(smap, inplace=True, match_other=True)  # Second attempt with add_false_negatives = False (default value)

>>> cnts = {'tp': 0, 'tn': 0, 'fp': 0, 'fn': 0}

>>> for contact in cmap:
        if contact.true_positive:
            cnts['tp'] += 1
        elif contact.false_positive:
            cnts['fp'] += 1
        elif contact.false_negative:
            cnts['fn'] += 1
        elif contact.true_negative:
            cnts['tn'] += 1
        else:
            continue

>>> cnts  # {'tp': 105, 'tn': 0, 'fp': 2950, 'fn': 0} --> No FNs in contact map, AS EXPECTED.

>>> for contact in smap:
        if contact.true_positive:
            cnts['tp'] += 1
        elif contact.false_positive:
            cnts['fp'] += 1
        elif contact.false_negative:
            cnts['fn'] += 1
        elif contact.true_negative:
            cnts['tn'] += 1
        else:
            continue

>>> cnts  # {'tp': 548, 'tn': 0, 'fp': 2950, 'fn': 0} --> TPs doubles + adds FNs. Right value should be {'tp': 210, 'tn': 0, 'fp': 2950, 'fn': 338}

```

**Comment by FilomenoSanchez** [comment] 2022-06-01 11:59
As discussed, this is not a bug, that behaviour is expected because all contacts in `structuremap` are marked as TPs in conkit.io.PDB lines 170-171:
```python
if distance_cutoff == 0 or distance < distance_cutoff:
    dist.true_positive = True
```

**Closed by FilomenoSanchez** 2022-06-01 11:59 UTC
